name: wids2020
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - omegaconf
    - hydra-core
    - hydra-zen
    - numpy>1.19.0
    - pyarrow
    - pandas>2.0.0
    - pandas_dq
    - skimpy
    - polars>0.19.0
    - polars-cli
    # - duckdb
    # - dbt-duckdb
    - ipykernel
    - jupyter
    - jupyter-cache
    # - quarto
    # - graphviz
    # - matplotlib
    # - seaborn
    - altair
    # - vega_datasets
    - d3blocks
    - plotly
    - ydata_profiling
    - jupyter-summarytools
    - scikit-learn>1.2.0
    - mlflow>2.0.0
    - lifelines
    - kaggle
    - xgboost
    - regex
    - featuretools
    - feature-engine
    - woodwork
    # Dependencies for scikit-survival that need to be installed before installing scikit-survival:
    - joblib
    - scipy>1.5.0
    - osqp  # This package needs cmake to be installed first. Use 'brew install cmake'
    - scikit-survival
    - prefect[viz]>=2.13.5
    - lightgbm
    - pycaret>=2.0.0
    - tpot
    - missingno
    - sidetable
    - miceforest
    - statsmodels
    - pygwalker