---
target_var: 'hospital_death'

train_test_split:
  random_state: 42
  train_ratio: 0.6
  validation_ratio: 0.15
  test_ratio: 0.25

numeric_features:
  - 'pre_icu_los_days'

categorical_features:
  - 'gender'
  - 'ethnicity'
  - 'hospital_admit_source'
  - 'icu_admit_source'

base_path: /Users/zacklarsen/Documents/Projects/kaggle-wids-datathon-2020
data_path: ${base_path}/data
model_path: ${base_path}/models
paths:
  mlflow:
    mlruns: ${base_path}/mlruns
  data:
    dictionary: ${data_path}/WiDS Datathon 2020 Dictionary.csv
    raw: ${data_path}/training_v2.csv
    typesafe: ${data_path}/typesafe.parquet
    clean: ${data_path}/clean.parquet
    X_train: ${data_path}/X_train.parquet
    X_test: ${data_path}/X_test.parquet
    X_validation: ${data_path}/X_validation.parquet
    y_train: ${data_path}/y_train.parquet
    y_test: ${data_path}/y_test.parquet
    y_validation: ${data_path}/y_validation.parquet
    X_transformed: ${data_path}/X_transformed.parquet
    y_pred: ${data_path}/y_pred.parquet
    submission: ${data_path}/submission.csv
  models:
    xgboost: ${model_path}/xgboost
    lightgbm: ${model_path}/lightgbm
    catboost: ${model_path}/catboost
    pycaret: ${model_path}/pycaret
    tpot: ${model_path}/tpot
