---
target_var: 'hospital_death'

train_test_split:
  random_state: 42
  train_ratio: 0.6
  validation_ratio: 0.15
  test_ratio: 0.25

numeric_features:
  - 'pre_icu_los_days'

categorical_features:
  - 'gender'
  - 'ethnicity'
  - 'hospital_admit_source'
  - 'icu_admit_source'

base_path: /Users/zacklarsen/Documents/Projects/kaggle-wids-datathon-2020
data_path: ${base_path}/data
raw_data_path: ${data_path}/raw
processed_data_path: ${data_path}/processed
model_path: ${base_path}/models
paths:
  mlflow:
    mlruns: ${base_path}/mlruns
  data:
    dictionary: ${raw_data_path}/WiDS Datathon 2020 Dictionary.csv
    train_raw: ${raw_data_path}/training_v2.csv
    test_raw: ${raw_data_path}/unlabeled.csv
    train_typed: ${processed_data_path}/train_typed.parquet
    test_typed: ${processed_data_path}/test_typed.parquet
    train_clean: ${processed_data_path}/train_clean.parquet
    X_train: ${processed_data_path}/X_train.parquet
    X_train_transformed: ${processed_data_path}/X_train_transformed.parquet
    X_test: ${processed_data_path}/X_test.parquet
    X_test_transformed: ${processed_data_path}/X_test_transformed.parquet
    X_validation: ${processed_data_path}/X_validation.parquet
    X_validation_transformed: ${processed_data_path}/X_validation_transformed.parquet
    y_train: ${processed_data_path}/y_train.parquet
    y_test: ${processed_data_path}/y_test.parquet
    y_validation: ${processed_data_path}/y_validation.parquet
    y_pred: ${processed_data_path}/y_pred.parquet
    submission: ${processed_data_path}/submission.csv
  models:
    lr: ${model_path}/lr/lr_clf.onnx
    xgboost: ${model_path}/xgboost
    lightgbm: ${model_path}/lightgbm
    catboost: ${model_path}/catboost
    pycaret: ${model_path}/pycaret
    tpot: ${model_path}/tpot
